environment:
  REDIS_URL: "${REDIS_URL}"

packages:
  - name: bench
    functions:
      - name: redis-bench
        runtime: python:3.13
        main: main
        web: true
        limits:
          timeout: 10000
          memory: 256
